pdp/member/urls.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, url

from pdp.member import views

urlpatterns = patterns(
    '',

    # Profile
    url(r'^voir/(?P<user_name>.+)$', views.details),
    url(r'^profil/editer$', views.edit_profile),

    # User's actions
    url(r'^publications$', views.publications),
    url(r'^actions$', views.actions),

    # Settings
    url(r'^parametres/profil$', views.settings_profile),
    url(r'^parametres/compte$', views.settings_account),

    url(r'^connexion$', views.login_view),
    url(r'^inscription$', views.register_view),
    url(r'^deconnexion/$', views.logout_view),
    url(r'^$', views.index),
)

pdp/urls.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.auth.models import User, Group

from haystack.views import SearchView
from haystack.forms import ModelSearchForm

from rest_framework import viewsets, routers

from django.contrib import admin
admin.autodiscover()

import pdp.pages.views
import pdp.settings

# ViewSets define the view behavior.

class UserViewSet(viewsets.ModelViewSet):
    model = User


class GroupViewSet(viewsets.ModelViewSet):
    model = Group


# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

urlpatterns = patterns(
    '',

    url(r'^articles/', include('pdp.article.urls')),
    url(r'^tutoriels/', include('pdp.tutorial.urls')),
    url(r'^forums/', include('pdp.forum.urls')),
    url(r'^messages/', include('pdp.messages.urls')),
    url(r'^membres/', include('pdp.member.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('pdp.pages.urls')),
    url(r'^galerie/', include('pdp.gallery.urls')),
    url(r'^api/', include('pdp.api.urls')),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^$', pdp.pages.views.home),

    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^api-docs/', include('rest_framework_swagger.urls')),
    url(r'^oauth2/', include('provider.oauth2.urls', namespace='oauth2')),

    url(r'^recherche/', SearchView(
        template='search/search.html',
        form_class=ModelSearchForm),
        name='haystack_search'),

    url(r'^robots\.txt$', pdp.pages.views.robots),

) + static(pdp.settings.MEDIA_URL, document_root=pdp.settings.MEDIA_ROOT)

# Serve debug toolbar files on debug
if pdp.settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)))

# Make Django serve the files if needed (local versions)
if pdp.settings.SERVE:
    urlpatterns += patterns(
        '',

        # Static content for website assets
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': pdp.settings.STATIC_ROOT}),

        # User-uploaded content
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': pdp.settings.MEDIA_ROOT}),
    )

pdp/member/models.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

"""Models for member app."""

from hashlib import md5

from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

from pdp.forum.models import Post, Topic
from pdp.tutorial.models import Tutorial
from pdp.article.models import Article


class Profile(models.Model):

    """Represents an user profile."""

    class Meta:
        verbose_name = 'Profil'
        verbose_name_plural = 'Profils'

    user = models.ForeignKey(User, unique=True, verbose_name=u'Utilisateur')

    site = models.CharField(u'Site internet', max_length=128, blank=True)
    show_email = models.BooleanField(u'Afficher adresse mail publiquement',
                                     default=True)

    avatar_url = models.CharField(
        u'URL de l\'avatar', max_length=128, null=True, blank=True
    )

    biography = models.TextField(u'Biographie', blank=True)

    def __unicode__(self):
        """Textual representation of a profile.

        Returns:
            string

        """
        return self.user.username

    def get_absolute_url(self):
        """Get URL to view this profile.

        Returns:
            string

        """
        return reverse('pdp.member.views.details', args=[self.user.username])

    def get_avatar_url(self):
        """Get the member's avatar URL.

        This will use custom URL or Gravatar.

        Returns:
            string

        """
        if self.avatar_url:
            return self.avatar_url
        else:
            return 'https://secure.gravatar.com/avatar/{0}?d=identicon'\
                .format(md5(self.user.email).hexdigest())

    def get_post_count(self):
        """Get total number of answers of the member on the forums.

        Returns:
            QuerySet on an integer.

        """
        return Post.objects.all().filter(author__pk=self.user.pk).count()

    def get_topic_count(self):
        """Get total number of topics created on the forums by the member.

        Returns:
            QuerySet on an integer.

        """
        return Topic.objects.all().filter(author=self.user).count()

    def get_followed_topics(self):
        """Get all the topics the user is currently following.

        Returns:
            QuerySet on Topic objects.

        """
        return Topic.objects.filter(topicfollowed__user=self.user)\
            .order_by('-last_message__pubdate')

    # Tutorial

    def get_tutorials(self):
        """Get all the tutorials written or being written by this member.

        Returns:
            QuerySet on Tutorial objects.

        """
        return Tutorial.objects.filter(authors=self.user.pk)

    def get_visible_tutorials(self):
        """Get all the tutorials published by this member.

        Returns:
            QuerySet on Tutorial objects.

        """
        return self.get_tutorials().filter(is_visible=True)

    def get_hidden_tutorials(self):
        """Get all the tutorials the member is currently writing.

        Returns:
            QuerySet on Tutorial objects.

        """
        return self.get_tutorials().filter(is_visible=False)

    # Article

    def get_articles(self):
        """Get all the articles written or being written by this member.

        Returns:
            QuerySet on Article objects.

        """
        return Article.objects.all().filter(author=self.user)

    def get_visible_articles(self):
        """Get all the articles published by this member.

        Returns:
            QuerySet on Article objects.

        """
        return self.get_articles().filter(is_visible=True)

    def get_hidden_articles(self):
        """Get all the articles the member is currently writing.

        Returns:
            QuerySet on Article objects.

        """
        return self.get_articles().filter(is_visible=False)

pdp/member/forms.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django import forms

from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from crispy_forms.helper import FormHelper
from crispy_forms_foundation.layout import Layout, Div, Fieldset, Submit, Field, HTML

from captcha.fields import CaptchaField

from pdp.member.models import Profile


class LoginForm(forms.Form):

    """Form used for login in users."""

    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=76, widget=forms.PasswordInput)


class RegisterForm(forms.Form):

    """Form used for to register new users."""

    email = forms.EmailField(label='Adresse email')
    username = forms.CharField(label='Nom d\'utilisateur', max_length=30)
    password = forms.CharField(
        label='Mot de passe', max_length=76, widget=forms.PasswordInput
    )
    password_confirm = forms.CharField(
        label='Confirmation', max_length=76, widget=forms.PasswordInput
    )
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            Fieldset(
                u'Identifiants',
                Field('username'),
                Field('password'),
                Field('password_confirm'),
                Field('email'),
            ),
            Fieldset(
                u'Captcha',
                Field('captcha'),
            ),
            Div(
                Submit('submit', 'Valider mon inscription'),
                HTML('<a href="/" class="button secondary">Annuler</a>'),
                css_class='button-group'
            )
        )
        super(RegisterForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()

        # Check that the password and it's confirmation match
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if not password_confirm == password:
            msg = u'Les mots de passe sont différents'
            self._errors['password'] = self.error_class([''])
            self._errors['password_confirm'] = self.error_class([msg])

            if 'password' in cleaned_data:
                del cleaned_data['password']

            if 'password_confirm' in cleaned_data:
                del cleaned_data['password_confirm']

        # Check that the user doesn't exist yet
        username = cleaned_data.get('username')
        if User.objects.filter(username=username).count() > 0:
            msg = u'Ce nom d\'utilisateur est déjà utilisé'
            self._errors['username'] = self.error_class([msg])

        return cleaned_data


# update extra information about user

class ProfileForm(forms.Form):
    biography = forms.CharField(
        label='Biographie',
        required=False,
        widget=forms.Textarea(
            attrs={'placeholder': 'Votre biographie au format Markdown.'}))
    site = forms.CharField(
        label='Site internet',
        required=False,
        max_length=128,
        widget=forms.TextInput(
            attrs={'placeholder': 'Lien vers votre site internet personnel '
                   '(ne pas oublier le http:// ou https:// devant).'}))
    show_email = forms.BooleanField(
        label='Afficher mon adresse mail publiquement',
        required=False)
    avatar_url = forms.CharField(
        label='Avatar',
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Lien vers un avatar externe '
                   '(laisser vide pour utiliser Gravatar).'}))

    def __init__(self, user, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.user = user
        profile = Profile.objects.get(user=self.user)

        # to get initial value form checkbox show email
        initial = kwargs.get('initial', {})
        value_checked = ''
        if 'show_email' in initial and initial['show_email']:
            value_checked = 'checked'

        self.helper.layout = Layout(
            Fieldset(
                u'Public',
                Field('biography'),
                Field('site'),
                Field('avatar_url'),
                # inline checkbox is not supported by crispy form
                HTML('<div id="div_id_show_email" class="ctrlHolder checkbox" style="padding-top:10px">\
                <label for="id_show_email" > <input id="id_show_email" type="checkbox" class="checkboxinput" name="show_email" ' + value_checked + '/>\
                Afficher mon adresse mail publiquement</label></div>'),
            ),
            Div(
                Submit('submit', 'Editer mon profil'),
                css_class='button-group'
            )
        )
        super(ProfileForm, self).__init__(*args, **kwargs)


# to update a password

class ChangePasswordForm(forms.Form):
    password_new = forms.CharField(
        label='Nouveau mot de passe ', max_length=76, widget=forms.PasswordInput)
    password_old = forms.CharField(
        label='Mot de passe actuel ', max_length=76, widget=forms.PasswordInput)
    password_confirm = forms.CharField(
        label='Confirmer le nouveau mot de passe ', max_length=76, widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.user = user

        self.helper.layout = Layout(
            Fieldset(
                u'Mot de passe',
                Field('password_old'),
                Field('password_new'),
                Field('password_confirm'),
            ),
            Div(
                Submit('submit', 'Changer mon mot de passe'),
                css_class='button-group'
            )
        )
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()

        password_old = cleaned_data.get('password_old')
        password_new = cleaned_data.get('password_new')
        password_confirm = cleaned_data.get('password_confirm')

        # Check if the actual password is not empty
        if password_old:
            user_exist = authenticate(
                username=self.user.username, password=password_old
            )
            if not user_exist and password_old != "":
                self._errors['password_old'] = self.error_class(
                    [u'Mot de passe incorrect.'])
                if 'password_old' in cleaned_data:
                    del cleaned_data['password_old']

        # Check that the password and it's confirmation match
        if not password_confirm == password_new:
            msg = u'Les mots de passe sont différents.'
            self._errors['password_new'] = self.error_class([msg])
            self._errors['password_confirm'] = self.error_class([msg])

            if 'password_new' in cleaned_data:
                del cleaned_data['password_new']

            if 'password_confirm' in cleaned_data:
                del cleaned_data['password_confirm']

        return cleaned_data

templates/member/actions.html
{% extends "member/base.html" %}

{% block title %}
    Panneau de contrôle
{% endblock %}

{% block headline %}
    Panneau de contrôle
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Panneau de contrôle</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <p>
            Bienvenue sur votre panneau de contrôle, celui-ci regroupe
            l’ensemble des opérations disponibles pour votre compte
            utitlisateur.
        </p>
    </div>
</div>

<div class="row">
    <div class="large-4 columns">
        <h2>Activité</h2>
        <ul>
            <li>
                <a href="{% url "pdp.member.views.details" user.username %}">
                    Voir votre profil
                </a>
            </li>
            <li>
                <a href="{% url "pdp.member.views.publications" %}">
                    Voir vos publications
                </a>
            </li>
        </ul>
    </div>
    <div class="large-4 columns">
        <h2>Configuration</h2>
        <ul>
            <li>
                <a href="{% url "pdp.member.views.settings_profile" %}">
                    Paramètres de votre profil
                </a>
            </li>
            <li>
                <a href="{% url "pdp.member.views.settings_account" %}">
                    Paramètres de votre compte
                </a>
            </li>
        </ul>
    </div>
    <div class="large-4 columns">
        <h2>Actions</h2>
        <ul>
            <li>
                <a href="{% url "pdp.member.views.logout_view" %}">
                    Se déconnecter
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <h2>Galeries</h2>
        <ul>
            <li>
                <a href="{% url "pdp.gallery.views.new_gallery" %}">
                    Créer une nouvelle galerie
                </a>
            </li>
            <li>
                <a href="{% url "pdp.gallery.views.gallery_list" %}">
                    Accéder à vos galeries
                </a>
            </li>
        </ul>
    </div>
</div>

{% endblock %}

templates/member/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Membres
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url "pdp.member.views.index" %}">Membres</a></li>
{% endblock %}

templates/member/edit_profile.html
{% extends "member/base.html" %}

{% block title %}
    Éditer mon profil
{% endblock %}

{% block headline %}
    Éditer mon profil
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ profile.user.get_absolute_url }}">{{ profile.user.username }}</a></li>
    <li class="current"><a href="#">Éditer mon profil</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <form action="" method="POST">
            <fieldset>
                <legend>Public</legend>

                <div class="control-group">
                    <label for="id_biography" class="control-label">Biographie</label>
                    <div class="controls">
                        <textarea name="biography" class="input-block-level" rows="10" id="id_biography"
                            placeholder="Votre biographie au format Markdown.">{{ profile.biography }}</textarea>
                    </div>
                </div>

                <div class="control-group">
                    <label for="id_site" class="control-label">Site internet</label>
                    <div class="controls">
                        <input type="text" name="site" id="id_site" class="input-block-level"
                        placeholder="Lien vers votre site internet personnel." value="{{ profile.site }}"/>
                    </div>
                </div>

                <div class="control-group">
                    <label for="id_email" class="control-label">Adresse mail</label>
                    <div class="controls">
                        <input type="text" name="email" id="id_email" class="input-block-level"
                        placeholder="Veuillez entrer une adresse email valide" value="{{ profile.user.email }}"/>
                    </div>
                </div>

                <div class="control-group">
                    <div class="controls">
                        <label class="checkbox">
                            <input type="checkbox" name="show_email"
                            {% if profile.show_email %}checked{% endif %}>
                            Afficher mon adresse mail publiquement
                        </label>
                    </div>
                </div>

            </fieldset>
            <div style="text-align: center;">
                <button type="submit" class="button">
                    <i class="icon-pencil icon-white"></i>
                    Éditer
                </button>

                <a href="{{ profile.user.get_absolute_url }}" class="button secondary">
                    Annuler
                </a>
            </div>

            {% csrf_token %}

        </form>
    </div>
</div>

{% endblock %}

templates/member/index.html
{% extends "member/base.html" %}
{% load profile %}

{% block title %}
    Liste des membres
{% endblock %}

{% block headline %}
    Membres
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Index</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <p>
            Sur cette page vous pourrez trouver la liste des membres inscrits
            au site (actuellement {{ members_count }} membres). Les membres les
            plus récents sont listés en premier.
        </p>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <ul class="large-block-grid-10 small-block-grid-4">
            {% for member in members %}
                <li style="text-align: center;">
                    {% include "member/member_item_common_big.part.html" %}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% include "misc/pagination.part.html" %}

{% endblock %}

templates/member/login.html
{% extends "member/base.html" %}

{% block title %}
    Connexion
{% endblock %}

{% block headline %}
    Se connecter
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Connexion</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        {% if not user.is_authenticated %}
            {% if error %}
            <div class="alert-box warning">
                {{ error }}.
            </div>
            {% endif %}

            <p>
                Si vous n'avez pas de compte, vous pouvez <a href="{% url "pdp.member.views.register_view" %}" >vous inscrire</a>.
            </p>
        {% else %}
            <p>
                Vous êtes déjà connecté.
            </p>
        {% endif %}
    </div>
</div>

{% if not user.is_authenticated %}
<div class="row">
    <div class="large-7 large-offset-1 columns">
        <form method="post" action="{% url "pdp.member.views.login_view" %}">
            <div class="row">
                <div class="small-4 columns">
                    <label class="right inline" for="id_username">Identifiant</label>
                </div>
                <div class="small-8 columns">
                    <input type="text" name="username" id="id_username" maxlength="30" {% if form.username.value %}value="{{ form.username.value }}"{% endif %} />
                </div>
            </div>
            <div class="row">
                <div class="small-4 columns">
                    <label class="right inline" for="id_password">Mot magique</label>
                </div>
                <div class="small-8 columns">
                    <input type="password" name="password" id="id_password" maxlength="76" />
                </div>
            </div>
            <div class="row">
                <div class="small-4 columns"></div>
                <div class="small-8 columns">
                    <label>
                        <input type="checkbox" name="remember">
                        Connexion automatique
                    </label>
                </div>
            </div>

            <div class="row">
                <div class="small-8 small-offset-4 columns">
                    <button type="submit" class="button">
                        Se connecter
                    </button>
                    <a href="/" class="button secondary">
                        Annuler
                    </a>
                </div>
            </div>

            {% csrf_token %}
        </form>
    </div>
</div>
{% endif %}

{% endblock %}

templates/member/logout.html
{% extends "member/base.html" %}

{% block title %}
    Déconnexion
{% endblock %}

{% block headline %}
    Se déconnecter
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Déconnexion</a></li>
{% endblock %}

{% block content %}

{% if not user.is_authenticated %}
    <div class="row">
        <div class="large-12 columns">
            <p>
                Vous n’êtes pas connecté.
            </p>
        </div>
    </div>
{% else %}
    <div class="row">
        <div class="large-6 large-centered columns">
            <form action="{% url "pdp.member.views.logout_view" %}" method="post">
                <input type="submit" class="button expand" value="Cliquez ici pour vous déconnecter" />
                {% csrf_token %}
            </form>
        </div>
    </div>
{% endif %}

{% endblock %}

templates/member/member_item_common.part.html
{% load profile %}

{% with profile=member|profile %}
<a href="{{ member.get_absolute_url }}" class="member-item">
    <img src="{{ profile.get_avatar_url }}" width="16" height="16" alt="" />
    {{ member.username }}
</a>
{% endwith %}

templates/member/member_item_common_big.part.html
{% load profile %}

{% with profile=member|profile %}
<a href="{{ member.get_absolute_url }}">
    <img src="{{ profile.get_avatar_url }}" width="64" height="64" alt="" style="width: 64px; height: 64px;"/><br />
    {{ member.username|truncatechars:12 }}
</a>
{% endwith %}

templates/member/publications.html
{% extends "member/base.html" %}

{% block title %}
    Publications
{% endblock %}

{% block headline %}
    Publications
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Publications</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <p>
            Cette page regroupe l’emsemble de vos publications rédigées sur le
            site, qu’elles soient en cours de rédaction, en bêta ou bien
            publiées.
        </p>
    </div>
</div>

{# Articles #}

<div class="row">
    <div class="large-12 columns">
        <h2>Mes articles</h2>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <a href="{% url "pdp.article.views.new" %}" class="button">
            <i class="icon-plus"></i>
            Nouvel article
        </a>
    </div>
</div>

{% if user_articles %}
    {% for article in user_articles %}
        {% if article.is_visible %}
            <div class="row article-publication-item published">
        {% else %}
            <div class="row article-publication-item">
        {% endif %}
            <div class="large-1 columns hide-for-small">
                <div class="date-box">
                    {% with date=article.pubdate %}
                        {% include "misc/datebox.part.html" %}
                    {% endwith %}
                </div>
            </div>
            <div class="large-10 small-10 columns">
                {% if article.is_beta %}<span class="label alert">BETA</span>{% endif %}
                {% if article.is_visible %}<span class="label success">PUBLIÉ</span>{% endif %}
                <a href="{{ article.get_absolute_url }}">{{ article.title }} </a>
            </div>
            <div class="large-1 small-2 columns">
                <a href="{{ article.get_edit_url }}" class="button small">
                    <i class="icon-edit"></i>
                    Éditer
                </a>
            </div>
        </div>
    {% endfor %}
{% else %}
    <div class="row">
        <div class="large-12 columns">
            <p>
                Aucun article n'a été rédigé.
            </p>
        </div>
    </div>
{% endif %}


{# Tutorials #}

<div class="row">
    <div class="large-12 columns">
        <h2>Mes tutoriels</h2>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <a href="{% url "pdp.tutorial.views.add_tutorial" %}" class="button">
            <i class="icon-plus"></i>
            Nouveau tutoriel
        </a>
    </div>
</div>

{% if user_tutorials %}
    {% for tutorial in user_tutorials %}
        {% if tutorial.is_visible %}
            <div class="row article-publication-item published">
        {% else %}
            <div class="row article-publication-item">
        {% endif %}
            <div class="large-1 columns hide-for-small">
                <div class="date-box">
                    {% with date=tutorial.pubdate %}
                        {% include "misc/datebox.part.html" %}
                    {% endwith %}
                </div>
            </div>
            <div class="large-10 small-10 columns">
                {% if tutorial.is_beta %}<span class="label alert">BETA</span>{% endif %}
                {% if tutorial.is_visible %}<span class="label success">PUBLIÉ</span>{% endif %}
                <a href="{{ tutorial.get_absolute_url }}">{{ tutorial.title }} </a>
            </div>
            <div class="large-1 small-2 columns">
                <a href="{% url "pdp.tutorial.views.edit_tutorial" %}?tutoriel={{ tutorial.pk }}" class="button small">
                    <i class="icon-edit"></i>
                    Éditer
                </a>
            </div>
        </div>
    {% endfor %}
{% else %}
    <div class="row">
        <div class="large-12 columns">
            <p>
                Aucun tutoriel n'a été rédigé.
            </p>
        </div>
    </div>
{% endif %}
{% endblock %}

templates/member/register_success.html
{% extends "member/base.html" %}

{% block title %}
    Inscription réussie
{% endblock %}

{% block headline %}
    Inscription réussie
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Inscription</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <p>
            Vous avez bien été inscrit au site. <a href="{% url "pdp.member.views.details" user.username %}">Voir votre profil</a>.
        </p>
    </div>
</div>

{% endblock %}