pdp/tutorial/urls.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, url

from pdp.tutorial import views
from pdp.tutorial import feeds

urlpatterns = patterns(
    '',

    url(r'^flux/rss/$', feeds.LastTutorialsFeedRSS(),
        name='tutorial-feed-rss'),
    url(r'^flux/atom/$', feeds.LastTutorialsFeedATOM(),
        name='tutorial-feed-atom'),

    # Viewing

    # Current URLs
    url(r'^voir/(?P<name>.+)$', views.find_tutorial),

    url(r'^(?P<tutorial_pk>\d+)/(?P<tutorial_slug>.+)/'
        r'(?P<part_slug>.+)/'
        r'(?P<chapter_slug>.+)/$',
        views.view_chapter, name="view-chapter-url"),

    url(r'^(?P<tutorial_pk>\d+)/(?P<tutorial_slug>.+)/'
        r'(?P<part_slug>.+)/$', views.view_part, name="view-part-url"),

    url(r'^(?P<tutorial_pk>\d+)/(?P<tutorial_slug>.+)/$',
        views.view_tutorial, name="view-tutorial-url"),

    url(r'^telecharger$', views.download),

    # Editing

    url(r'^editer/tutoriel$', views.edit_tutorial),
    url(r'^modifier/tutoriel$', views.modify_tutorial),
    url(r'^modifier/partie$', views.modify_part),
    url(r'^editer/partie$', views.edit_part),
    url(r'^modifier/chapitre$', views.modify_chapter),
    url(r'^editer/chapitre$', views.edit_chapter),
    url(r'^modifier/extrait$', views.modify_extract),
    url(r'^editer/extrait$', views.edit_extract),

    # Adding

    url(r'^nouveau/tutoriel$', views.add_tutorial),
    url(r'^nouveau/partie$', views.add_part),
    url(r'^nouveau/chapitre$', views.add_chapter),
    url(r'^nouveau/extrait$', views.add_extract),

    url(r'^$', views.index),
)

pdp/urls.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.auth.models import User, Group

from haystack.views import SearchView
from haystack.forms import ModelSearchForm

from rest_framework import viewsets, routers

from django.contrib import admin
admin.autodiscover()

import pdp.pages.views
import pdp.settings

# ViewSets define the view behavior.

class UserViewSet(viewsets.ModelViewSet):
    model = User


class GroupViewSet(viewsets.ModelViewSet):
    model = Group


# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

urlpatterns = patterns(
    '',

    url(r'^articles/', include('pdp.article.urls')),
    url(r'^tutoriels/', include('pdp.tutorial.urls')),
    url(r'^forums/', include('pdp.forum.urls')),
    url(r'^messages/', include('pdp.messages.urls')),
    url(r'^membres/', include('pdp.member.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('pdp.pages.urls')),
    url(r'^galerie/', include('pdp.gallery.urls')),
    url(r'^api/', include('pdp.api.urls')),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^$', pdp.pages.views.home),

    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^api-docs/', include('rest_framework_swagger.urls')),
    url(r'^oauth2/', include('provider.oauth2.urls', namespace='oauth2')),

    url(r'^recherche/', SearchView(
        template='search/search.html',
        form_class=ModelSearchForm),
        name='haystack_search'),

    url(r'^robots\.txt$', pdp.pages.views.robots),

) + static(pdp.settings.MEDIA_URL, document_root=pdp.settings.MEDIA_ROOT)

# Serve debug toolbar files on debug
if pdp.settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)))

# Make Django serve the files if needed (local versions)
if pdp.settings.SERVE:
    urlpatterns += patterns(
        '',

        # Static content for website assets
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': pdp.settings.STATIC_ROOT}),

        # User-uploaded content
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': pdp.settings.MEDIA_ROOT}),
    )

pdp/tutorial/models.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

"""Models for tutorial app.

The class hierarchy is as follows :
 - "large" tutorials: Tutorial < Parts < Chapters
 - "small" tutorials : Tutorial < Chapter

"""
import os
import string

from django.db import models
from django.db.models.signals import post_save

from django.dispatch import receiver
from django.conf import settings
from django.contrib.auth.models import User

from django.core.urlresolvers import reverse
from django.core.files.uploadedfile import SimpleUploadedFile

from PIL import Image
from cStringIO import StringIO

from pdp.tutorial.exceptions import CorruptedTutorialError, \
    OrphanPartException, OrphanChapterException

from pdp.utils import slugify
from pdp.utils.models import has_changed

IMAGE_MAX_WIDTH = 64
IMAGE_MAX_HEIGHT = 64


def image_path(instance, filename):
    """Get path to a tutorial image.

    Returns:
        string

    """
    ext = filename.split('.')[-1]
    filename = u'original.{}'.format(string.lower(ext))
    return os.path.join('tutorials', str(instance.pk), filename)


def thumbnail_path(instance, filename):
    """Get path to a tutorial thumbnail.

    Returns:
        string

    """
    ext = filename.split('.')[-1]
    filename = u'thumb.{}'.format(string.lower(ext))
    return os.path.join('tutorials', str(instance.pk), filename)


class Tutorial(models.Model):

    """A tutorial, large or small."""

    class Meta:
        verbose_name = u'Tutoriel'
        verbose_name_plural = u'Tutoriels'

    SMALL = 'S'
    MEDIUM = 'M'
    BIG = 'B'

    SIZE_CHOICES = (
        (SMALL, u'Mini'),
        (MEDIUM, u'Standard'),
        (BIG, u'Étendu'),
    )

    title = models.CharField(u'Titre', max_length=80)
    description = models.CharField(u'Description', max_length=200)
    authors = models.ManyToManyField(User, verbose_name=u'Auteurs')

    image = models.ImageField(upload_to=image_path,
                              blank=True, null=True, default=None)
    thumbnail = models.ImageField(upload_to=thumbnail_path,
                                  blank=True, null=True, default=None)

    introduction = models.TextField(u'Introduction', null=True, blank=True)
    conclusion = models.TextField(u'Conclusion', null=True, blank=True)

    slug = models.SlugField(max_length=80)

    pubdate = models.DateTimeField(u'Date de publication', blank=True)

    # We could distinguish large/small tutorials by looking at what chapters
    # are contained directly in a tutorial, but that'd be more complicated
    # than a field.
    size = models.CharField(u'Taille du tutoriel', max_length=1,
                            choices=SIZE_CHOICES, default=BIG)

    is_visible = models.BooleanField(u'Est visible publiquement',
                                     default=False)
    is_pending = models.BooleanField(u'Est en attente', default=False)
    is_beta = models.BooleanField(u'Est en bêta', default=False)

    def __unicode__(self):
        """Textual representation of a tutorial.

        Returns:
            string

        """
        return self.title

    def get_absolute_url(self):
        """Get URL to view this tutorial.

        Returns:
            string

        """
        return reverse('pdp.tutorial.views.view_tutorial', args=[
            self.pk, slugify(self.title)
        ])

    def get_pdf_url(self):
        """Get URL to get a PDF file of this tutorial."""
        return u'{}/tutorials/{}/{}.pdf'.format(
            settings.MEDIA_URL,
            self.pk,
            self.slug,
        )

    def has_pdf(self):
        """Check if the tutorial has a PDF file."""
        return os.path.isfile(os.path.join(
            settings.MEDIA_ROOT,
            'tutorials',
            str(self.pk),
            u'{}.pdf'.format(self.slug),
        ))

    def get_edit_url(self):
        """Get URL to edit this tutorial.

        Returns:
            string

        """
        return u'/tutoriel/editer?tutoriel={0}'.format(self.pk)

    def get_parts(self):
        """Get the parts associated with the tutorial if it's big.

        Returns:
            list of Part

        """
        return Part.objects.all()\
            .filter(tutorial__pk=self.pk)\
            .order_by('position_in_tutorial')

    def get_chapter(self):
        """Get the chapter associated with the tutorial if it's small.

        Returns:
            Chapter

        Raises:
            CorruptedTutorialError

        """
        if not self.size == Tutorial.SMALL:
            return None

        try:
            # We can use get since we know there'll only be one chapter
            return Chapter.objects.get(tutorial__pk=self.pk)
        except Chapter.DoesNotExist:
            # Whoops, this tutorial is broken!
            raise CorruptedTutorialError('Small tutorial missing its chapter')

    def save(self, force_update=False, force_insert=False,
             thumb_size=(IMAGE_MAX_HEIGHT, IMAGE_MAX_WIDTH)):
        """Save tutorial instance.

        If tutorial's image was changed, it will update its thumbnail field
        resizing it. Then it will call normal saving of the model.

        """
        self.slug = slugify(self.title)

        if has_changed(self, 'image') and self.image:
            # TODO : delete old image

            image = Image.open(self.image)

            if image.mode not in ('L', 'RGB'):
                image = image.convert('RGB')

            image.thumbnail(thumb_size, Image.ANTIALIAS)

            # save the thumbnail to memory
            temp_handle = StringIO()
            image.save(temp_handle, 'png')
            temp_handle.seek(0)  # rewind the file

            # save to the thumbnail field
            suf = SimpleUploadedFile(os.path.split(self.image.name)[-1],
                                     temp_handle.read(),
                                     content_type='image/png')
            self.thumbnail.save(u'{}.png'.format(suf.name), suf, save=False)

            # save the image object
            super(Tutorial, self).save(force_update, force_insert)
        else:
            super(Tutorial, self).save()


def get_last_tutorials():
    """Get the last published tutorials.

    This should be used for the home page tutorial displaying.

    Returns:
        list of Tutorial

    """
    return Tutorial.objects.all() \
        .filter(is_visible=True) \
        .order_by('-pubdate')[:5]


class Part(models.Model):

    """A part, containing chapters."""

    class Meta:
        verbose_name = u'Partie'
        verbose_name_plural = u'Parties'

    # A part has to belong to a tutorial, since only tutorials with parts
    # are large tutorials
    tutorial = models.ForeignKey(Tutorial, verbose_name=u'Tutoriel parent')
    position_in_tutorial = models.IntegerField(u'Position dans le tutoriel',
                                               null=True, blank=True)

    title = models.CharField(u'Titre', max_length=80)

    introduction = models.TextField(u'Introduction')
    conclusion = models.TextField(u'Conclusion')

    slug = models.SlugField(max_length=80)

    # The list of chapters is shown between introduction and conclusion

    def save(self, *args, **kwargs):
        """Save a part.

        This will compute the slug field from title field and then save the
        model.

        """
        self.slug = slugify(self.title)
        super(Part, self).save(*args, **kwargs)

    def __unicode__(self):
        """Textual representation of a part.

        Returns:
            string

        """
        return u'<Partie pour {0}, {1}>'\
            .format(self.tutorial.title, self.position_in_tutorial)

    def get_absolute_url(self):
        """Get URL to view the part.

        Returns:
            string

        """
        if self.tutorial.size == "B":
            return reverse('pdp.tutorial.views.view_part', args=[
                self.tutorial.pk,
                self.tutorial.slug,
                self.slug,
            ])
        else:
            return reverse('pdp.tutorial.views.view_tutorial', args=[
                self.tutorial.pk,
                self.tutorial.slug,
            ])

    def get_chapters(self):
        """Get all the chapters of the part.

        Returns:
            Chapter list

        """
        return Chapter.objects.all()\
            .filter(part=self).order_by('position_in_part')


class Chapter(models.Model):

    """A chapter, containing some extracts."""

    class Meta:
        verbose_name = 'Chapitre'
        verbose_name_plural = 'Chapitres'

    # A chapter may belong to a part, that's where the difference between large
    # and small tutorials is.
    part = models.ForeignKey(Part, null=True, blank=True,
                             verbose_name='Partie parente')
    image = models.ImageField(upload_to=image_path, blank=True, null=True)
    thumbnail = models.ImageField(upload_to=image_path, blank=True, null=True)

    position_in_part = models.IntegerField('Position dans la partie',
                                           null=True, blank=True)

    # This field is required in order to use pagination in chapters, see the
    # update_position_in_tutorial() method.
    position_in_tutorial = models.IntegerField('Position dans le tutoriel',

templates/tutorial/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Tutoriels
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url "pdp.tutorial.views.index" %}">Tutoriels</a></li>
{% endblock %}

{% block menu_tutorial %}
    class="active"
{% endblock %}

templates/tutorial/chapter_common.part.html
{# File describing the point of chapters #}

<div class="row">
    <div class="large-12 columns">
        <p>
            Les chapitres sont le coeur du contenu de vos tutoriels ; ils permettent
            de décrire de manière précise telle ou telle notion en utilisant des
            définitions, des exemples, etc.
        </p>
    </div>
</div>

templates/tutorial/edit_chapter.html
{% extends "tutorial/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Éditer le chapitre
{% endblock %}

{% block headline %}
    Éditer le chapitre
{% endblock %}

{% block breadcrumb %}
{% if chapter.tutorial %}
    <li><a href="{{ chapter.tutorial.get_absolute_url }}">{{ chapter.tutorial.title }}</a></li>
{% else %}
    <li><a href="{{ chapter.part.tutorial.get_absolute_url }}">{{ chapter.part.tutorial.title }}</a></li>
    <li><a href="{{ chapter.part.get_absolute_url }}">{{ chapter.part.title }}</a></li>
    <li><a href="{{ chapter.get_absolute_url }}">{{ chapter.title }}</a></li>
{% endif %}
    <li class="current"><a href="#">Éditer le chapitre</a></li>
{% endblock %}

{% block content %}

{% if chapter.part %}
<div class="row">
    <div class="large-12 columns">
        {% include "tutorial/chapter_common.part.html" %}
    </div>
</div>
{% endif %}

<div class="row">
    <div class="large-12 columns">
        {% crispy form %}
    </div>
</div>

{% endblock %}

templates/tutorial/edit_part.html
{% extends "tutorial/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Éditer la partie
{% endblock %}

{% block headline %}
    Éditer la partie
{% endblock %}

{% block headline-sub %}
    {{ part.title }}
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ part.tutorial.get_absolute_url }}">{{ part.tutorial.title }}</a></li>
    <li><a href="{{ part.get_absolute_url }}">{{ part.title }}</a></li>
    <li class="current"><a href="#">Éditer la partie</a></li>
{% endblock %}

{% block content %}

{% include "tutorial/part_common.part.html" %}

<div class="row">
    <div class="large-12 columns">
        {% crispy form %}
    </div>
</div>

{% endblock %}

templates/tutorial/edit_tutorial.html
{% extends "tutorial/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Éditer le tutoriel
{% endblock %}

{% block headline %}
    Éditer le tutoriel
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ tutorial.get_absolute_url }}">{{ tutorial.title }}</a></li>
    <li class="current"><a href="#">Éditer le tutoriel</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-6 columns">
        <h2>Général</h2>
        {% crispy form %}
    </div>
    <div class="large-6 columns">
        <h2>Auteurs</h2>

        <form action="{% url "pdp.tutorial.views.modify_tutorial" %}" method="post">
            <div class="row collapse">
                <div class="small-10 columns">
                    <input type="text" name="author" placeholder="Nom de l'utilisateur à ajouter…" />
                </div>
                <div class="small-2 columns">
                    <button type="submit" class="button" name="add_author">
                        Ajouter
                    </button>
                </div>
            </div>
            <input type="hidden" name="tutorial" value="{{ tutorial.pk }}" />
            {% csrf_token %}
        </form>

        <form action="{% url "pdp.tutorial.views.modify_tutorial" %}" method="post">
            <table>
                <thead>
                    <th>Auteur</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    {% for member in tutorial.authors.all %}
                        <tr>
                            <td>{% include "member/member_item_common.part.html" %}</td>
                            <td>
                                {% if tutorial.authors.count > 1 %}
                                <button type="submit" name="author" value="{{ member.pk }}">
                                    Supprimer
                                </button>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <input type="hidden" name="remove_author" value="1" />
            <input type="hidden" name="tutorial" value="{{ tutorial.pk }}" />
            {% csrf_token %}
        </form>

    </div>
</div>

{% endblock %}

templates/tutorial/feeds.part.html
<a href="#" class="button secondary dropdown" data-dropdown="tutorials-drop-feeds">
    Flux
</a><br />
<ul id="tutorials-drop-feeds" class="f-dropdown">
    <li><a href="{% url "tutorial-feed-rss" %}">Nouveaux tutoriels (RSS)</a></li>
    <li><a href="{% url "tutorial-feed-atom" %}">Nouveaux tutoriels (ATOM)</a></li>
</ul>

templates/tutorial/find_tutorial.html
{% extends "tutorial/base.html" %}
{% load humane_date %}
{% load profile %}
{% load emarkdown %}

{% block title %}
    Tutoriels rédigés par {{ usr.username }}
{% endblock %}

{% block headline %}
    Tutoriels rédigés par {{ usr.username }}
{% endblock %}

{% block breadcrumb %}
    {% with profile=usr|profile %}
        <li ><a href="{{ profile.get_absolute_url }}">{{ usr.username }}</a></li>
    {% endwith %}
    <li ><a href="{% url "pdp.tutorial.views.find_tutorial" usr.username %}">Tutoriels rédigés</a></li>
    <li class="current"><a href="#">Recherche</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <table>
          <thead>
            <tr>
              <th width="15%">Tutoriels</th>
              <th width="10%">Quand</th>
              <th width="30%">Introduction</th>
            </tr>
          </thead>
          <tbody>
            {% for tuto in tutos %}
            <tr>
                <td>
                    <div>
                        {% if tuto.thumbnail %}
                            <img src="{{ tuto.thumbnail.url }}" />
                        {% endif %}
                        <a href="{{ tuto.get_absolute_url }}">{{ tuto.title }} </a> 
                        {% if tuto.description %} <p> {{ tuto.description }} </p> {% endif %}
                    </div>
                </td>
                <td>
                    {% with date=tuto.pubdate|humane_date %}
                        {{ date }}
                    {% endwith %}
                </td>
                <td>
                    {{ tuto.introduction|truncatechars:200|emarkdown }}
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>

{% endblock %}

templates/tutorial/index.html
{% extends "tutorial/base.html" %}
{% load cache %}

{% block title %}
    Liste des tutoriels
{% endblock %}

{% block meta %}
    <meta name="description" content="Les tutoriels vous permettent d'apprendre sur divers sujets axés autour de la programmation et de l'informatique." />
{% endblock %}

{% block header %}
    <h1>
        <i class="icon-book icon-large"></i>
        Tutoriels
    </h1>
    <p>
        Les tutoriels vous permettent <strong>d'apprendre</strong> sur divers sujets axés autour de la programmation et de l'informatique.
    </p>
{% endblock %}

{% block headline %}
    Liste des tutoriels
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Index</a></li>
{% endblock %}

{% block headline-actions %}
    <div class="button-group">
        {% include "tutorial/feeds.part.html" %}
        {% if user.is_authenticated %}
            <a href="{% url "pdp.tutorial.views.add_tutorial" %}" class="button">
                <i class="icon-plus"></i>
                Nouveau tutoriel
            </a>
        {% endif %}
    </div>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <h2>À la une</h2>
        {% cache 120 tutorials-index %}
            {% if tutorials %}
                <div class="tutorial-items">
                    {% for tuto in tutorials %}
                        {% include "tutorial/tutorial_item.part.html" %}
                    {% endfor %}
                </div>
            {% else %}
                <p>Aucun tutoriel disponible.</p>
            {% endif %}
        {% endcache %}
    </div>
</div>

{# Validation stuff #}

{% if perms.tutorial.change_tutorial %}
<div class="row">
    <div class="large-12 columns">
        <h2>En attente de validation</h2>
        {% cache 120 tutorials-pending %}
        {% if pending_tutorials %}
            <div class="tutorial-items">
                {% for tuto in pending_tutorials %}
                    <div class="row article-publication-item">
                        <div class="small-1 columns">
                            {% with date=tuto.pubdate %}
                                {% include "misc/datebox.part.html" %}
                            {% endwith %}
                        </div>
                        <div class="small-8 columns">
                            <a href="{{ tuto.get_absolute_url }}">{{ tuto.title }}</a>
                            <p>{{ tuto.description }}</p>
                        </div>
                        <div class="small-3 columns">
                            <form action="{% url "pdp.tutorial.views.modify_tutorial" %}" method="post">
                                <div class="button-group even-2 expand">
                                    <button type="submit" class="button success" name="validate">
                                        Valider
                                    </button>
                                    <button type="submit" class="button alert" name="refuse">
                                        Refuser
                                    </button>
                                </div>
                                <input type="hidden" name="tutorial" value="{{ tuto.pk }}">
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>Aucun tutoriel en attente de validation.</p>
        {% endif %}
        {% endcache %}
    </div>
</div>
{% endif %}

{% endblock %}

templates/tutorial/new_chapter.html
{% extends "tutorial/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Nouveau chapitre
{% endblock %}

{% block headline %}
    Nouveau chapitre
{% endblock %}

{% block headline-sub %}
    {{ part.title }}
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ part.tutorial.get_absolute_url }}">{{ part.tutorial.title }}</a></li>
    {% if part.tutorial.size != "M" %}
        <li><a href="{{ part.get_absolute_url }}">{{ part.title }}</a></li>
    {% endif %}
    <li class="current"><a href="#">Nouveau chapitre</a></li>
{% endblock %}

{% block content %}

{% include "tutorial/chapter_common.part.html" %}

<div class="row">
    <div class="large-12 columns">
        {% crispy form %}
    </div>
</div>

{% endblock %}

templates/tutorial/part_common.part.html
{# File describing the point of parts #}

<div class="row">
    <div class="large-12 columns">
        <p>
            Les parties permettent, dans le cas de tutoriels conséquents, d'organiser
            les différents chapitres de votre tutoriel en sections. Typiquement, on
            pourra envisager une partie permettant la découvetre de la notion, une
            autre concernant l'approfondissement puis une troisième en tant qu'annexe.
        </p>
    </div>
</div>

templates/tutorial/tutorial_item_small.part.html
{% load static %}

{# TODO: use a custom css class for this kind of elements #}
<div class="row collapse">
    <div class="small-2 column">
        {% if tutorial.thumbnail %}
            <img src="{{ tutorial.thumbnail.url }}" alt="" width="64px" />
        {% else %}
            <img src="{% static "img/tutorial-blank.png" %}" alt="" width="64px" />
        {% endif %}
    </div>
    <div class="small-10 column" style="padding-left: 5px;">
        <a href="{{ tutorial.get_absolute_url }}">{{ tutorial.title }}</a>
        <p>{{ tutorial.description }}</p>
    </div>
</div>

templates/tutorial/view_part.html
{% extends "tutorial/base.html" %}

{% block title %}
    {{ part.title }} ({{ part.tutorial.title }})
{% endblock %}

{% block headline %}
    Partie {{ part.position_in_tutorial }} : {{ part.title }}
    {% if part.tutorial.is_beta %}
        <small><span class="label alert">BETA</span></small>
    {% endif %}
    <br />
    <small>{{ part.tutorial.title }}</small>
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ part.tutorial.get_absolute_url }}">{{ part.tutorial.title }}</a></li>
    <li class="current"><a href="#">{{ part.title }}</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        {% include "tutorial/view_part_common.part.html" %}
    </div>
</div>

{% endblock %}