pdp/article/urls.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, url

from pdp.article import views
from pdp.article import feeds

urlpatterns = patterns(
    '',

    url(r'^flux/rss/$', feeds.LastArticlesFeedRSS(), name='article-feed-rss'),
    url(r'^flux/atom/$', feeds.LastArticlesFeedATOM(),
        name='article-feed-atom'),

    # TODO: Handle redirect

    url(r'^voir/(?P<article_pk>\d+)-(?P<article_slug>.+)$',
        views.deprecated_view_redirect),
    url(r'^(?P<article_pk>\d+)/(?P<article_slug>.+)$', views.view),

    url(r'^telecharger$', views.download),

    url(r'^nouveau$', views.new),
    url(r'^editer$', views.edit),
    url(r'^modifier$', views.modify),
    url(r'^auteur/(?P<name>.+)$', views.find_article),

    url(r'^tags/$', views.tags),
    url(r'^tag/(?P<name>.+)$', views.tag),

    url(r'^categorie/(?P<name>.+)$', views.category, name="articles_category"),

    url(r'^$', views.index),
)

pdp/urls.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.auth.models import User, Group

from haystack.views import SearchView
from haystack.forms import ModelSearchForm

from rest_framework import viewsets, routers

from django.contrib import admin
admin.autodiscover()

import pdp.pages.views
import pdp.settings

# ViewSets define the view behavior.

class UserViewSet(viewsets.ModelViewSet):
    model = User


class GroupViewSet(viewsets.ModelViewSet):
    model = Group


# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

urlpatterns = patterns(
    '',

    url(r'^articles/', include('pdp.article.urls')),
    url(r'^tutoriels/', include('pdp.tutorial.urls')),
    url(r'^forums/', include('pdp.forum.urls')),
    url(r'^messages/', include('pdp.messages.urls')),
    url(r'^membres/', include('pdp.member.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('pdp.pages.urls')),
    url(r'^galerie/', include('pdp.gallery.urls')),
    url(r'^api/', include('pdp.api.urls')),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^$', pdp.pages.views.home),

    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^api-docs/', include('rest_framework_swagger.urls')),
    url(r'^oauth2/', include('provider.oauth2.urls', namespace='oauth2')),

    url(r'^recherche/', SearchView(
        template='search/search.html',
        form_class=ModelSearchForm),
        name='haystack_search'),

    url(r'^robots\.txt$', pdp.pages.views.robots),

) + static(pdp.settings.MEDIA_URL, document_root=pdp.settings.MEDIA_ROOT)

# Serve debug toolbar files on debug
if pdp.settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)))

# Make Django serve the files if needed (local versions)
if pdp.settings.SERVE:
    urlpatterns += patterns(
        '',

        # Static content for website assets
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': pdp.settings.STATIC_ROOT}),

        # User-uploaded content
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': pdp.settings.MEDIA_ROOT}),
    )

pdp/article/models.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

"""Models for article app."""

import os
import string

from django.db import models
from django.db.models.signals import post_save

from django.conf import settings

from django.dispatch import receiver
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from taggit.managers import TaggableManager

from pdp.utils import slugify
from pdp.utils.models import has_changed

from PIL import Image
from cStringIO import StringIO
from django.core.files.uploadedfile import SimpleUploadedFile

IMAGE_MAX_WIDTH = 64
IMAGE_MAX_HEIGHT = 64


def image_path(instance, filename):
    """Return path to an article image.

    Returns:
        string

    """
    ext = filename.split('.')[-1]
    filename = u'original.{}'.format(string.lower(ext))
    return os.path.join('articles', str(instance.pk), filename)


def thumbnail_path(instance, filename):
    """Return path to an article thumbnail.

    Returns:
        string

    """
    ext = filename.split('.')[-1]
    filename = u'thumb.{}'.format(string.lower(ext))
    return os.path.join('articles', str(instance.pk), filename)


class ArticleCategory(models.Model):

    """A way to organize article in different category."""

    class Meta:
        verbose_name = u'Catégorie d’article'
        verbose_name_plural = u'Catégories d’article'

    title = models.CharField(u'Titre', max_length=80)
    slug = models.SlugField(max_length=80)

    def __unicode__(self):
        """Textual representation of a category.

        Returns:
            string

        """
        return self.title

    def get_absolute_url(self):
        """Get URL to view the category.

        Returns:
            string

        """
        return reverse('pdp.article.views.category', args=(
            self.slug,
        ))

    def get_article_count(self):
        """Return number of articles in this category."""
        return Article.objects.filter(category__pk=self.pk).count()


class Article(models.Model):

    """An article."""

    class Meta:
        verbose_name = u'Article'
        verbose_name_plural = u'Articles'

    title = models.CharField(u'Titre', max_length=80)
    description = models.CharField(u'Description', max_length=200)

    text = models.TextField(u'Texte')

    author = models.ForeignKey(User, verbose_name=u'Auteur',
                               related_name='articles')

    slug = models.SlugField(max_length=80)

    pubdate = models.DateTimeField(u'Date de publication', blank=True)

    tags = TaggableManager()

    image = models.ImageField(upload_to=image_path,
                              blank=True, null=True, default=None)
    thumbnail = models.ImageField(upload_to=thumbnail_path,
                                  blank=True, null=True, default=None)

    is_visible = models.BooleanField(u'Est visible publiquement',
                                     default=False)
    is_pending = models.BooleanField(u'Est en attente', default=False)
    is_beta = models.BooleanField(u'Est visible par les membres',
                                  default=False)

    category = models.ForeignKey(ArticleCategory, null=True, blank=True,
                                 verbose_name=u'Catégorie')

    def __unicode__(self):
        """Textual representation of an article.

        Returns:
            string

        """
        return self.title

    def get_absolute_url(self):
        """Get URL to view the article.

        Returns:
            string

        """
        return reverse('pdp.article.views.view', args=(
            self.pk, self.slug,
        ))

    def get_pdf_url(self):
        """Get URL to get a PDF file of this article."""
        return u'{}/articles/{}/{}.pdf'.format(
            settings.MEDIA_URL,
            self.pk,
            self.slug,
        )

    def get_edit_url(self):
        """Get URL to edit the article.

        Returns:
            string

        """
        return '/articles/editer?article={0}'.format(self.pk)

    def get_download_url(self):
        return u'{}?article={}'.format(
            reverse('pdp.article.views.download'),
            self.pk)

    def save(self, force_update=False, force_insert=False,
             thumb_size=(IMAGE_MAX_HEIGHT, IMAGE_MAX_WIDTH)):
        """Save the article.

        This will save thumbnail on disk and then save the model in database.

        """
        self.slug = slugify(self.title)

        if has_changed(self, 'image') and self.image:
            # TODO : delete old image

            image = Image.open(self.image)

            if image.mode not in ('L', 'RGB'):
                image = image.convert('RGB')

            image.thumbnail(thumb_size, Image.ANTIALIAS)

            # save the thumbnail to memory
            temp_handle = StringIO()
            image.save(temp_handle, 'png')
            temp_handle.seek(0)  # rewind the file

            # save to the thumbnail field
            suf = SimpleUploadedFile(os.path.split(self.image.name)[-1],
                                     temp_handle.read(),
                                     content_type='image/png')
            self.thumbnail.save('{}.png'.format(suf.name), suf, save=False)

            # save the image object
            super(Article, self).save(force_update, force_insert)
        else:
            super(Article, self).save()


def get_last_articles():
    """Get the last published articles.

    This should be used for the home page article displaying.

    Returns:
        list of Article

    """
    return Article.objects.all()\
        .filter(is_visible=True)\
        .order_by('-pubdate')[:5]


def get_prev_article(g_article):
    """Try to get the previous article ordered by pubdate.

    If g_article is the first article ever, None will be returned.

    Returns:
        Article

    """
    try:
        return Article.objects\
            .filter(is_visible=True)\
            .filter(pubdate__lt=g_article.pubdate)\
            .order_by('-pubdate')[0]
    except IndexError:
        return None


def get_next_article(g_article):
    """Try to get the next article ordered by pubdate.

    If g_article is the last one, None will be returned.

    Returns:
        Article

    """
    try:
        return Article.objects\
            .filter(is_visible=True)\
            .filter(pubdate__gt=g_article.pubdate)\
            .order_by('pubdate')[0]
    except IndexError:
        return None


@receiver(post_save, sender=Article)
def saved_article_handler(sender, **kwargs):
    """Function called on each article save."""
    from pdp.utils.articles import export_article_pdf
    export_article_pdf(kwargs.get('instance', None))

pdp/article/forms.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms_foundation.layout import Layout, Submit, Field, HTML

from pdp.article.models import ArticleCategory

class NewArticleForm(forms.Form):
    title = forms.CharField(
        label=u'Titre',
        max_length=80
    )

    description = forms.CharField(
        max_length=200
    )

    image = forms.ImageField(
        label=u'Icône',
        required=False)

    tags = forms.CharField(
        label=u'Tags (séparés par une virgule)',
        max_length=80,
        required=False
    )

    category = forms.ModelChoiceField(
        label=u'Catégorie',
        queryset=ArticleCategory.objects.all(),
        required=False
    )

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            Field('title'),
            Field('description'),
            Field('image'),
            Field('tags'),
            Field('category'),
            Submit('submit', u'Créer l’article'),
        )
        super(NewArticleForm, self).__init__(*args, **kwargs)


class EditArticleForm(forms.Form):
    title = forms.CharField(
        label=u'Titre',
        max_length=80
    )

    description = forms.CharField(
        max_length=200
    )

    text = forms.CharField(
        label=u'Texte',
        required=False,
        widget=forms.Textarea
    )

    image = forms.ImageField(
        label=u'Icône',
        required=False)

    tags = forms.CharField(
        label=u'Tags (séparés par une virgule)',
        max_length=80,
        required=False
    )

    category = forms.ModelChoiceField(
        label=u'Catégorie',
        queryset=ArticleCategory.objects.all(),
        required=False
    )

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            Field('title'),
            Field('description'),
            HTML('{% include "misc/editor.part.html" %}'),
            Field('text'),
            Field('image'),
            Field('tags'),
            Field('category'),
            Submit('submit', u'Enregistrer les modifications'),
        )
        super(EditArticleForm, self).__init__(*args, **kwargs)

templates/article/article_item.part.html
{% load static %}

<div class="row article-publication-item">
    <div class="large-1 small-2 columns">
        {% if article.thumbnail %}
            <img src="{{article.thumbnail.url }}" alt="" width="64px" />
        {% else %}
        <img src="{% static "img/article-blank.png" %}" alt="" width="64px" />
        {% endif %}
    </div>
    <div class="large-10 small-10 columns">
        <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
        {% if article.is_beta %}<span class="label alert">BETA</span>{% endif %}
        <p>{{ article.description }}</p>
    </div>
    <div class="small-1 columns hide-for-small">
        <div class="date-box">
            {% with date=article.pubdate %}
                {% include "misc/datebox.part.html" %}
            {% endwith %}
        </div>
    </div>
</div>

templates/article/article_item_small.part.html
{% load static %}

{# TODO: use a custom css class for this kind of elements #}
<div class="row collapse">
    <div class="small-2 columns">
        {% if article.thumbnail %}
            <img src="{{ article.thumbnail.url }}" alt="" width="64px" />
        {% else %}
            <img src="{% static "img/article-blank.png" %}" alt="" width="64px" />
        {% endif %}
    </div>
    <div class="small-10 columns" style="padding-left: 5px;">
        <a href="{{ article.get_absolute_url }}">{{ article.title }}</a><br />
        <p>{{ article.description }}</p>
    </div>
</div>

templates/article/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Articles
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url "pdp.article.views.index" %}">Articles</a></li>
{% endblock %}

{% block menu_article %}
    class="active"
{% endblock %}

templates/article/category.html
{% extends "article/base.html" %}
{% load static %}

{% block title %}
    {{ category.title }}
{% endblock %}

{% block headline %}
    {{ category.title }}
{% endblock %}

{% block breadcrumb %}
    <li class="unavailable"><a href="#">Par catégorie</a></li>
    <li class="current"><a href="#">{{ category.title }}</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <dl class="sub-nav">
            <dt>Catégorie :</dt>

            <dd class="{% ifequal category.slug "tous" %}active{% endifequal %}">
                <a href="{% url "articles_category" "tous" %}">Tous</a>
            </dd>

            {% for c in all_category %}
                <dd class="{% ifequal category.slug c.slug %}active{% endifequal %}">
                    <a href="{{ c.get_absolute_url }}">{{ c.title }} ({{ c.get_article_count }})</a>
                </dd>
            {% endfor %}
 
            {% if user.is_authenticated %}
                <dd class="{% ifequal category.slug "beta" %}active{% endifequal %}">
                    <a href="{% url "articles_category" "beta" %}">Bêta</a>
                </dd>
            {% endif %}
        </dl>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        {% if articles %}
            <div class="article-items">
                {% for article in articles %}
                    {% include "article/article_item.part.html" %}
                {% endfor %}
            </div>
        {% else %}
            <p>Aucun article disponible.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/article/edit.html
{% extends "article/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Éditer
{% endblock %}

{% block headline %}
    Éditer l'article
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></li>
    <li class="current"><a href="#">Éditer</a></li>
{% endblock %}

{% block content %}

{% if article.is_visible %}
    <div class="row">
        <div class="large-12 columns">
            <div class="alert-box warning">
                <strong>Cet article est actuellement en ligne !</strong> Veuillez être particulièrement prudent au niveau des changements que vous apportez à celui-ci.
                Vous pouvez modifier la forme de celui-ci, mais évitez d'en modifier le fond !
            </div>
        </div>
    </div>
{% endif %}

<div class="row">
    <div class="large-12 columns">
        {% crispy form %}
    </div>
</div>

{% endblock %}

templates/article/feeds.part.html
<a href="#" class="button secondary dropdown" data-dropdown="articles-drop-feeds">
    Flux
</a><br />
<ul id="articles-drop-feeds" class="f-dropdown">
    <li><a href="{% url "article-feed-rss" %}">Nouveaux articles (RSS)</a></li>
    <li><a href="{% url "article-feed-atom" %}">Nouveaux articles (ATOM)</a></li>
</ul>

templates/article/find_article.html
{% extends "article/base.html" %}
{% load humane_date %}
{% load profile %}
{% load emarkdown %}

{% block title %}
    Articles rédigés par {{ usr.username }}
{% endblock %}

{% block headline %}
    Articles rédigés par {{ usr.username }}
{% endblock %}

{% block breadcrumb %}
    {% with profile=usr|profile %}
        <li ><a href="{{ profile.get_absolute_url }}">{{ usr.username }}</a></li>
    {% endwith %}
    <li ><a href="{% url "pdp.article.views.find_article" usr.username %}">Articles rédigés</a></li>
    <li class="current"><a href="#">Recherche</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <table>
          <thead>
            <tr>
              <th width="15%">Article</th>
              <th width="10%">Quand</th>
              <th width="30%">Extrait</th>
            </tr>
          </thead>
          <tbody>
            {% for article in articles %}
            <tr>
                <td>
                    <div>
                        {% if article.thumbnail %}
                            <img src="{{ article.thumbnail.url }}" />
                        {% endif %}
                        <a href="{{ article.get_absolute_url }}">{{ article.title }} </a> 
                        {% if article.description %} <p> {{ article.description }} </p> {% endif %}
                    </div>
                </td>
                <td>
                    {% with date=article.pubdate|humane_date %}
                        {{ date }}
                    {% endwith %}
                </td>
                <td>
                    {{ article.text|truncatechars:200|emarkdown }}
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>

{% endblock %}

templates/article/index.html
{% extends "article/base.html" %}
{% load cache %}
{% load taggit_extras %}

{% block title %}
    Liste des articles
{% endblock %}

{% block meta %}
    <meta name="description" content="Les articles sont rédigés par la communauté ; ils permettent aussi bien de se tenir informé des dernières innovations du moment que de découvrir de nouvelles notions liées aux différents domaines de l'informatique." />
{% endblock %}

{% block header %}
    <h1>
        <i class="icon-file-text icon-large"></i>
        Articles
    </h1>
    <p>
        Les articles sont rédigés par la communauté ; ils permettent aussi bien
        de <strong>se tenir informé des dernières innovations</strong> du
        moment que de <strong>découvrir de nouvelles notions</strong> liées aux
        différents domaines de l'informatique.
    </p>
{% endblock %}

{% block headline %}
    Liste des articles
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Index</a></li>
{% endblock %}

{% block headline-actions %}
    <div class="button-group">

        {% include "article/feeds.part.html" %}

        {% if user.is_authenticated %}
            <a href="{% url "pdp.article.views.new" %}" class="button">
                <i class="icon-plus"></i>
                Nouvel article
            </a>
        {% endif %}

    </div>
{% endblock %}

{% block content %}

{% get_tagcloud as tags for 'article.Article' %}

<div class="row">
    <div class="large-12 columns">
        <h2>À la une</h2>

        {% cache 120 articles-index %}
        {% if articles %}
            <div class="article-items">
                {% for article in articles %}
                    {% include "article/article_item.part.html" %}
                {% endfor %}
            </div>
            <a href="{% url "articles_category" "tous" %}" class="button">
                Voir tous les articles
            </a>
        {% else %}
            <p>Aucun article disponible.</p>
        {% endif %}
        {% endcache %}

    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <h2>Catégories</h2>

        <ul class="inline-list">
            <li><a href="{% url "articles_category" "tous" %}">Tout les articles</a></li>
            {% for category in all_article_category %}
                <li><a href="{{ category.get_absolute_url }}">{{ category }} ({{ category.get_article_count }})</a></li>
            {% endfor %}
            {% if user.is_authenticated %}
                <li><a href="{% url "articles_category" "beta" %}">Bêta</a></li>
            {% endif %}
        </ul>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <h2>Tags</h2>
        <p>Voici le nuage des tags utilisés sur les différents articles actuellement publiés sur le site :</p>
        {% for tag in tags %}
            {% if tag.name %}
                {% with weight=tag.weight|floatformat:0 %}
                    <a href="{% url "pdp.article.views.tag" name=tag.name %}"
                        class="label secondary"
                        style="font-size: {{ tag.weight|add:13 }}px">
                        {{ tag.name }}
                    </a>
                {% endwith %}
            {% endif %}
        {% endfor %}
    </div>
</div>


{# Validation stuff #}

{% if perms.article.change_article %}
<div class="row">
    <div class="large-12 columns">
        <h2>Articles en attente de validation</h2>
        {% cache 120 articles-pending %}
        {% if pending_articles %}
            <div class="article-items">
                {% for article in pending_articles %}
                    <div class="row article-publication-item">
                        <div class="small-1 columns">
                            {% with date=article.pubdate %}
                                {% include "misc/datebox.part.html" %}
                            {% endwith %}
                        </div>
                        <div class="small-8 columns">
                            <a href="{{ article.get_absolute_url }}">
                                {{ article.title }}
                            </a>
                            <p>
                                {{ article.description }}
                            </p>
                        </div>
                        <div class="small-3 columns">
                            <form action="{% url "pdp.article.views.modify" %}" method="post">
                                <div class="button-group even-2 expand">
                                    <button type="submit" class="button success" name="validate">
                                        Valider
                                    </button>
                                    <button type="submit" class="button alert" name="refuse">
                                        Refuser
                                    </button>
                                </div>
                                <input type="hidden" name="article" value="{{ article.pk }}">
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>Aucun article en attente de validation.</p>
        {% endif %}
        {% endcache %}
    </div>
</div>
{% endif %}

{% endblock %}

templates/article/new.html
{% extends "article/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Nouveau
{% endblock %}

{% block headline %}
    Nouvel article
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Nouvel article</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        {% crispy form %}
    </div>
</div>

{% endblock %}

templates/article/tag.html
{% extends "article/base.html" %}
{% load taggit_extras %}

{% block title %}
    {{ tagname }}
{% endblock %}

{% block headline %}
    {{ tagname }}
{% endblock %}

{% block breadcrumb %}
    <li><a href="{% url "pdp.article.views.tags" %}">Tags</a></li>
    <li class="current"><a href="#">{{ tagname }}</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        {% if articles %}
            <ul>
                {% for article in articles %}
                    <li>
                        <a href="{{ article.get_absolute_url }}">
                            {{ article.title }}
                        </a>
                        {% for tag in article.tags.all %}
                            {% if tag.name %}
                            <a href="{% url "pdp.article.views.tag" name=tag.name %}"
                                class="label {% if not tag.name == tagname %}secondary{% endif %}">
                                {{ tag.name }}
                            </a>
                            {% endif %}
                        {% endfor %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>
                Aucun article n’est associé à ce tag.
                <a href="{% url "pdp.article.views.tags" %}">
                    Retour à la liste des tags
                </a>
            </p>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/article/tags.html
{% extends "article/base.html" %}
{% load taggit_extras %}

{% block title %}
    Tags
{% endblock %}

{% block headline %}
    Liste des tags
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Liste des tags</a></li>
{% endblock %}

{% block content %}

{% get_tagcloud as tags for 'article.Article' %}

<div class="row">
    <div class="large-12 columns">
        <p>
            Voici le nuage des tags utilisés sur les différents articles
            actuellement publiés sur le site :
        </p>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        {% for tag in tags %}
            {% if tag.name %}
                {% with weight=tag.weight|floatformat:0 %}
                    <a href="{% url "pdp.article.views.tag" name=tag.name %}"
                        class="label secondary"
                        style="font-size: {{ tag.weight|add:13 }}px">
                        {{ tag.name }}
                    </a>
                {% endwith %}
            {% endif %}
        {% endfor %}
    </div>
</div>


{% endblock %}

templates/article/view_pager.part.html
<div class="row">
    <div class="large-6 columns">
        {% if prev %}
            <a class="button secondary" href="{{ prev.get_absolute_url }}">
                « {{ prev.title }}
            </a>
        {% endif %}
    </div>
    <div class="large-6 columns">
        <div class="right">
            {% if next %}
               <a class="button secondary" href="{{ next.get_absolute_url }}">
                   {{ next.title }} »
               </a>
           {% endif %}
        </div>
    </div>
</div>