pdp/forum/urls.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, url

from pdp.forum import views
from pdp.forum import feeds

urlpatterns = patterns(
    '',

    # Feeds
    url(r'^flux/rss/$', views.deprecated_feed_messages_rss),
    url(r'^flux/atom/$', views.deprecated_feed_messages_atom),

    url(r'^flux/messages/rss/$', feeds.LastPostsFeedRSS(),
        name='post-feed-rss'),
    url(r'^flux/messages/atom/$', feeds.LastPostsFeedATOM(),
        name='post-feed-atom'),

    url(r'^flux/sujets/rss/$', feeds.LastTopicsFeedRSS(),
        name='topic-feed-rss'),
    url(r'^flux/sujets/atom/$', feeds.LastTopicsFeedATOM(),
        name='topic-feed-atom'),

    # Deprecated URLs, have to be checked before new ones to avoid conflict
    url(r'^sujet/(?P<topic_pk>\d+)-(?P<topic_slug>.+)$',
        views.deprecated_topic_redirect),
    url(r'^(?P<cat_slug>.+)/(?P<forum_pk>\d+)-(?P<forum_slug>.+)/$',
        views.deprecated_details_redirect),
    url(r'^(?P<cat_pk>\d+)-(?P<cat_slug>.+)/$',
        views.deprecated_cat_details_redirect),

    # Viewing a thread
    url(r'^sujet/nouveau$', views.new),
    url(r'^sujet/editer$', views.edit),
    url(r'^sujet/(?P<topic_pk>\d+)/(?P<topic_slug>.+)$', views.topic),
    url(r'^sujets/(?P<name>.+)', views.find_topic),

    # Message-related
    url(r'^message/editer$', views.edit_post),
    url(r'^message/nouveau$', views.answer),
    url(r'^message/utile$', views.useful_post),
    url(r'^messages/(?P<name>.+)$', views.find_post),

    # Forum details
    url(r'^(?P<cat_slug>.+)/(?P<forum_slug>.+)/$',
        views.details),

    # Forums belonging to one category
    url(r'^(?P<cat_slug>.+)/$', views.cat_details),

    # Home
    url(r'^$', views.index),

    # Followed topics
    url(r'^suivis$', views.followed_topics),
)

pdp/urls.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.auth.models import User, Group

from haystack.views import SearchView
from haystack.forms import ModelSearchForm

from rest_framework import viewsets, routers

from django.contrib import admin
admin.autodiscover()

import pdp.pages.views
import pdp.settings

# ViewSets define the view behavior.

class UserViewSet(viewsets.ModelViewSet):
    model = User


class GroupViewSet(viewsets.ModelViewSet):
    model = Group


# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

urlpatterns = patterns(
    '',

    url(r'^articles/', include('pdp.article.urls')),
    url(r'^tutoriels/', include('pdp.tutorial.urls')),
    url(r'^forums/', include('pdp.forum.urls')),
    url(r'^messages/', include('pdp.messages.urls')),
    url(r'^membres/', include('pdp.member.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('pdp.pages.urls')),
    url(r'^galerie/', include('pdp.gallery.urls')),
    url(r'^api/', include('pdp.api.urls')),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^$', pdp.pages.views.home),

    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^api-docs/', include('rest_framework_swagger.urls')),
    url(r'^oauth2/', include('provider.oauth2.urls', namespace='oauth2')),

    url(r'^recherche/', SearchView(
        template='search/search.html',
        form_class=ModelSearchForm),
        name='haystack_search'),

    url(r'^robots\.txt$', pdp.pages.views.robots),

) + static(pdp.settings.MEDIA_URL, document_root=pdp.settings.MEDIA_ROOT)

# Serve debug toolbar files on debug
if pdp.settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)))

# Make Django serve the files if needed (local versions)
if pdp.settings.SERVE:
    urlpatterns += patterns(
        '',

        # Static content for website assets
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': pdp.settings.STATIC_ROOT}),

        # User-uploaded content
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': pdp.settings.MEDIA_ROOT}),
    )

pdp/forum/models.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

"""Models for forum app."""

from math import ceil

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from pdp.utils import get_current_user
from pdp.utils.cache import template_cache_delete


class Category(models.Model):

    """A category, containing forums."""

    class Meta:
        verbose_name = u'Catégorie'
        verbose_name_plural = u'Catégories'

    title = models.CharField(u'Titre', max_length=80)
    position = models.IntegerField(u'Position', null=True, blank=True)
    slug = models.SlugField(max_length=80)

    def __unicode__(self):
        """Textual representation of a category.

        Returns:
            string

        """
        return self.title

    def get_absolute_url(self):
        """Get URL to view the category.

        Returns:
            string

        """
        return u'/forums/{0}/'.format(self.slug)

    def get_forums(self):
        """Retreive all forums owned by the category.

        Returns:
            QuerySet on Forum objects

        """
        return Forum.objects.all()\
            .filter(category=self)\
            .order_by('position_in_category')


class Forum(models.Model):

    """A forum, containing topics."""

    class Meta:
        verbose_name = u'Forum'
        verbose_name_plural = u'Forums'

    title = models.CharField(u'Titre', max_length=80)
    subtitle = models.CharField(u'Sous-titre', max_length=200, blank=True)

    category = models.ForeignKey(Category, verbose_name=u'Catégorie')
    position_in_category = models.IntegerField(u'Position dans la catégorie',
                                               null=True, blank=True)

    slug = models.SlugField(max_length=80)

    def __unicode__(self):
        """Textual representation of a forum.

        Returns:
            string

        """
        return self.title

    def get_absolute_url(self):
        """Get URL to view the forum.

        Returns:
            string

        """
        return u'/forums/{0}/{1}/'.format(
            self.category.slug,
            self.slug,
        )

    def get_topic_count(self):
        """Get the number of threads in the forum.

        Returns:
            QuerySet on integer

        """
        return Topic.objects.all().filter(forum__pk=self.pk).count()

    def get_post_count(self):
        """Get the number of posts in the forum.

        Returns:
            QuerySet on integer

        """
        return Post.objects.all().filter(topic__forum=self).count()

    def get_last_message(self):
        """Get the last message on the forum, if any.

        Returns:
            Post object or None

        """
        try:
            return Post.objects.all()\
                .filter(topic__forum__pk=self.pk)\
                .order_by('-pubdate')[0]
        except IndexError:
            return None

    def is_read(self):
        """Check if this forum was read by current user.

        Returns:
            boolean

        """
        for t in Topic.objects.all().filter(forum=self):
            if never_read(t):
                return False
        return True


class Topic(models.Model):

    """A thread, containing posts."""

    class Meta:
        verbose_name = u'Sujet'
        verbose_name_plural = u'Sujets'

    title = models.CharField(u'Titre', max_length=80)
    subtitle = models.CharField(u'Sous-titre', max_length=200, blank=True)

    forum = models.ForeignKey(Forum, verbose_name=u'Forum')
    author = models.ForeignKey(User, verbose_name=u'Auteur',
                               related_name='topics')
    last_message = models.ForeignKey('Post', null=True,
                                     related_name='last_message',
                                     verbose_name=u'Dernier message')
    pubdate = models.DateTimeField(u'Date de création', auto_now_add=True)

    is_solved = models.BooleanField(u'Est résolu', default=False)
    is_locked = models.BooleanField(u'Est verrouillé', default=False)
    is_sticky = models.BooleanField(u'Est en post-it', default=False)

    def __unicode__(self):
        """Textual representation of a topic.

        Returns:
            string

        """
        return self.title

    def get_absolute_url(self):
        """Get URL to view the topic.

        Returns:
            string

        """
        return u'/forums/sujet/{0}/{1}'.format(self.pk, slugify(self.title))

    def get_post_count(self):
        """Return the number of posts in the topic.

        Returns:
            QuerySet on integer

        """
        return Post.objects.all().filter(topic__pk=self.pk).count()

    def get_last_answer(self):
        """Gets the last answer in the thread, if any.

        Returns:
            Post object or None

        """
        try:
            last_post = Post.objects.all()\
                .filter(topic__pk=self.pk)\
                .order_by('-pubdate')[0]
        except IndexError:
            return None

        # We do not want first post to be considered as an answer.
        if last_post == self.first_post():
            return None
        else:
            return last_post

    def first_post(self):
        """Return the first post of a topic, written by topic's author.

        Returns:
            Post object or None

        """
        try:
            return Post.objects\
                .filter(topic=self)\
                .order_by('pubdate')[0]
        except IndexError:
            return None

    def last_read_post(self):
        """Return the last post the user has read.

        Returns:
            Post object or None

        """
        user = get_current_user()

        if user is not None:
            # Logged-in user, so he may have a TopicRead instance
            try:
                return TopicRead.objects\
                    .select_related()\
                    .filter(topic=self, user=user)\
                    .latest('post__pubdate').post
            except TopicRead.DoesNotExist:
                return self.first_post()

        # Anonymous user, we return the last post since the first one is
        # available using the topic title link so it would have been redundant.
        resp = self.get_last_answer()
        return resp if resp is not None else self.first_post()

    def is_followed(self, user=None):
        """Check if the topic is currently followed by the user.

        This method uses the TopicFollowed objects.

        Returns:
            boolean

        """
        if user is None:
            user = get_current_user()

        try:
            TopicFollowed.objects.get(topic=self, user=user)
        except TopicFollowed.DoesNotExist:
            return False
        return True

    def antispam(self, user=None):
        """Check if the user is allowed to post in a topic.

        This method uses the SPAM_LIMIT_SECONDS value. If user shouldn't be
        able to post, then antispam is activated and this method returns True.
        Otherwise time elapsed between user's last post and now is enough, and
        the method will return False.

        Returns:
            boolean

        """
        if user is None:
            user = get_current_user()

        last_user_posts = Post.objects\
            .filter(topic=self)\
            .filter(author=user)\
            .order_by('-pubdate')

        if last_user_posts and last_user_posts[0] == self.get_last_answer():
            last_user_post = last_user_posts[0]
            t = timezone.now() - last_user_post.pubdate
            if t.total_seconds() < settings.SPAM_LIMIT_SECONDS:
                return True

        return False

    def never_read(self):
        return never_read(self)


class Post(models.Model):

    """A forum post written by an user."""

    topic = models.ForeignKey(Topic, verbose_name=u'Sujet')
    author = models.ForeignKey(User, verbose_name=u'Auteur',
                               related_name='posts')
    text = models.TextField(u'Texte')

    pubdate = models.DateTimeField(u'Date de publication', auto_now_add=True)
    update = models.DateTimeField(u'Date d\'édition', null=True, blank=True)

    position_in_topic = models.IntegerField(u'Position dans le sujet')

    is_useful = models.BooleanField(u'Est utile', default=False)

    def __unicode__(self):
        """Textual representation of a post.

        Returns:
            string

        """
        return u'<Post pour "{0}", #{1}>'.format(self.topic, self.pk)

    def get_absolute_url(self):
        """Get URL to view the post.

        Returns:
            string

        """
        page = int(ceil(
            float(self.position_in_topic) / settings.POSTS_PER_PAGE
        ))

        return '{0}?page={1}#p{2}'\
            .format(self.topic.get_absolute_url(), page, self.pk)


class TopicRead(models.Model):

    """Small model which keeps track of the user viewing topics.

    It remembers the topic he looked and what was the last Post at this time.

    """

    class Meta:
        verbose_name = u'Sujet lu'
        verbose_name_plural = u'Sujets lus'

    topic = models.ForeignKey(Topic)
    post = models.ForeignKey(Post)

pdp/forum/forms.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django import forms


class TopicForm(forms.Form):
    title = forms.CharField(max_length=80)
    subtitle = forms.CharField(max_length=255, required=False)
    text = forms.CharField(widget=forms.Textarea)


class PostForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)

templates/forum/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Forums
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url "pdp.forum.views.index" %}">Forums</a></li>
{% endblock %}

{% block menu_forum %}
    class="active"
{% endblock %}

templates/forum/cat_details.html
{% extends "forum/base.html" %}

{% block title %}
    {{ category.title }}
{% endblock %}

{% block headline %}
    {{ category.title }}
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="javascript:;">{{ category.title }}</a></li>
{% endblock %}

{% block content %}
    
{% include "forum/forums_common.part.html" %}

{% endblock %}

templates/forum/edit_post.html
{% extends "forum/base.html" %}

{% block title %}
    Éditer un message
{% endblock %}

{% block headline %}
    Éditer un message
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ post.topic.forum.category.get_absolute_url }}">{{ post.topic.forum.category.title }}</a></li>
    <li><a href="{{ post.topic.forum.get_absolute_url }}">{{ post.topic.forum.title }}</a></li>
    <li><a href="{{ post.topic.get_absolute_url }}">{{ post.topic.title }}</a></li>
    <li class="current"><a href="javascript:;">Éditer un message</a></li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <form action="#previsualisation" method="POST">
            {% if topic %}
            <fieldset>
                <legend>Sujet</legend>
                <div class="control-group">
                    <label class="control-label" for="id_title">Titre</label>
                    <div class="controls">
                        <input type="text" name="title" id="id_title"
                            class="input-xxlarge" value="{{ topic.title }}" />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_subtitle">Sous titre</label>
                    <div class="controls">
                        <input type="text" name="subtitle" id="id_subtitle"
                            class="input-xxlarge" value="{{ topic.subtitle }}" />
                    </div>
                </div>
            </fieldset>
            {% endif %}
            {% include "misc/editor.part.html" %}
            <fieldset>
                <legend>Message</legend>
                <div class="control-group">
                    <label class="control-label" for="id_text">Texte</label>
                    <div class="controls">
                        <textarea id="id_text" name="text"
                            class="input-block-level" rows="20">{{ text }}</textarea>
                    </div>
                </div>
            </fieldset>

            <div style="text-align: center;">
                <button type="submit" class="button">
                    Éditer
                </button>

                <button type="submit" name="preview" class="button secondary">
                    Prévisualisation
                </button>

                <a href="{{ post.get_absolute_url }}" class="button secondary">Annuler</a>
            </div>

            {% csrf_token %}
        </form>
    </div>
</div>

{% include "forum/previsualization.part.html" %}

{% endblock %}

templates/forum/topic.html
{% extends "forum/base.html" %}
{% load emarkdown %}
{% load humane_date %}
{% load profile %}

{% block title %}
    {{ topic.title }}
{% endblock %}

{% block headline %}
    <a href="{{ topic.get_absolute_url }}">
        {{ topic.title }}
    </a>
{% endblock %}

{% block headline-sub %}
    {{ topic.subtitle }}
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ topic.forum.category.get_absolute_url }}">{{ topic.forum.category.title }}</a></li>
    <li><a href="{{ topic.forum.get_absolute_url }}">{{ topic.forum.title }}</a></li>
    <li class="current"><a href="javascript:;">{{ topic.title }}</a></li>
{% endblock %}

{% block headline-actions %}
    {% if user.is_authenticated %}
        <form action="{% url "pdp.forum.views.edit" %}" method="POST"
        class="topic-actions" id="edit_form">
            <input type="hidden" name="topic" value="{{ topic.pk }}" />
            <input type="hidden" name="page" value="{{ nb }}">
            <div class="button-group">
                <a href="/forums/sujet/nouveau?forum={{ topic.forum.pk }}" class="button small">
                    <i class="icon-plus"></i>
                    Nouveau
                </a>
                {% if topic.author.pk == user.pk %}
                <button type="submit" name="solved" id="resolu_btn" class="button small {% if topic.is_solved %}success{% else %}secondary{% endif %}">
                    <i class="icon-ok"></i>
                    {% if topic.is_solved %}
                        Résolu
                    {% else %}
                        Résolu ?
                    {% endif %}
                </button>
                {% endif %}
                <button class="button small {% if not topic.is_followed %}secondary{% endif %}" type="submit" name="follow" id="follow_btn">
                    <i class="icon-star"></i>
                    {% if topic.is_followed %}
                        Suivi
                    {% else %}
                        Suivre
                    {% endif %}
                </button>
            </div>

            {% csrf_token %}
        </form>

        {% if perms.forum.change_topic %}
            <form action="{% url "pdp.forum.views.edit" %}" method="POST" class="topic-actions">
                <input type="hidden" name="topic" value="{{ topic.pk }}" />

                <a href="#" class="button secondary dropdown" data-dropdown="staff-dropdown">
                    Staff
                </a>
                <div id="staff-dropdown" class="f-dropdown content" data-dropdown-content>
                    <div class="switch">
                        <input id="lock-off" name="lock" type="radio" {% if not topic.is_locked %}checked="checked"{% endif %}>
                        <label for="lock-off" onclick="">Verouiller</label>

                        <input id="lock-on" name="lock" type="radio" {% if topic.is_locked %}checked="checked"{% endif %}>
                        <label for="lock-on" onclick="">Verouillé</label>

                        <span></span>
                    </div>

                    <div class="switch">
                        <input id="sticky-off" name="sticky" type="radio" {% if not topic.is_sticky %}checked="checked"{% endif %}>
                        <label for="sticky-off" onclick="">Post-it</label>

                        <input id="sticky-on" name="sticky" type="radio" {% if topic.is_sticky %}checked="checked"{% endif %}>
                        <label for="sticky-on" onclick="">Post-it</label>

                        <span></span>
                    </div>

                    <div class="switch">
                        <input id="solved-off" name="solved" type="radio" {% if not topic.is_solved %}checked="checked"{% endif %}>
                        <label for="solved-off" onclick="">Résolu</label>

                        <input id="solved-on" name="solved" type="radio" {% if topic.is_solved %}checked="checked"{% endif %}>
                        <label for="solved-on" onclick="">Résolu</label>

                        <span></span>
                    </div>

                    <a href="javascript:;" class="button validate">
                        Valider
                    </a>
                </div>

                {% csrf_token %}
            </form>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}

<div class="row" id="resolu" {% if not topic.is_solved %}style="display: none;"{% endif %}>
    <div class="large-12 columns">
        <div class="alert-box success">
            <strong>Ce sujet est résolu</strong>, l'auteur de ce sujet a trouvé une
            solution à son problème.
        </div>
    </div>
</div>

{% include "forum/topic_pagination.part.html" with position="top" %}


{% for post in posts %}
<div class="post {% if forloop.first and nb > 1 %}before{% endif %} {% if post.is_useful %}useful{% endif %}">
        <div class="row post-head" id="p{{ post.id }}">
            <div class="large-2 columns post-nickname">
                <p>
                    <a href="{{ post.author.get_absolute_url }}">
                        {{ post.author.username }}
                    </a>
                </p>
            </div>
            <div class="large-10 columns">
                <div class="right">
                    {% if user.is_authenticated %}
                        <div class="button-group">
                            {% if topic.author == user and post.author != user %}
                                <a href="/forums/message/utile?message={{ post.pk }}" class="button small {% if not post.is_useful %}secondary{% else %}success{% endif %}">
                                    <i class="icon-thumbs-up"></i>
                                    Cette réponse m'a aidé
                                </a>
                            {% endif %}

                            {% if post.author == user or perms.forum.change_post %}
                                <a href="/forums/message/editer?message={{ post.pk }}" class="button secondary small">
                                    <i class="icon-pencil"></i>
                                    Éditer
                                </a>
                            {% endif %}

                            {% if not topic.is_locked and not topic.antispam %}
                                <a href="/forums/message/nouveau?sujet={{ topic.pk }}&amp;cite={{ post.pk }}"
                                    class="button secondary small">
                                    <i class="icon-quote-left"></i>
                                    Citer
                                </a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
                <p>
                    <a href="#p{{ post.pk }}">#</a>
                    {{ post.pubdate|humane_date }}
                    {% if not post.update = None %}
                        (dernière édition {{ post.update|humane_date }})
                    {% endif %}
                    {% if forloop.first and nb > 1 %}
                        &ndash; page précédente
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="row post-content">
            <div class="large-2 columns hide-for-small post-avatar">
                {% with profile=post.author|profile %}
                    <img src="{{ profile.get_avatar_url }}" width="80" height="80" alt="" />
                {% endwith %}
            </div>
            <div class="large-10 columns">
                {{ post.text|emarkdown }}
            </div>
        </div>
    </div>
{% endfor %}

{% include "forum/topic_pagination.part.html" with position="bottom" %}

{% if user.is_authenticated %}
<hr />
<form action="{% url "pdp.forum.views.answer" %}?sujet={{ topic.pk }}"
method="POST" id="submit_form">
    <div class="row">
        <div class="large-12 columns">
            <h3>Ajouter une réponse</h3>
            {% include "misc/editor.part.html" %}
            <textarea id='id_text' name="text" rows="10" {% if topic.is_locked or topic.antispam %}disabled{% endif %}
                placeholder="Votre message au format Markdown.">{% spaceless %}
                    {% if topic.is_locked %}
                        Ce sujet est verrouillé.
                    {% elif topic.antispam  %}
                        Vous ne pouvez pas encore poster dans ce sujet (protection antispam de 15 min).
                    {% endif %}
                {% endspaceless %}</textarea>
        </div>
    </div>
    <div class="row">
        <div class="large-8 large-centered columns" style="text-align: center;">
            <button class="button btn-primary" type="submit" {% if topic.is_locked or topic.antispam %}disabled{% endif %}>
                <i class="icon-reply"></i>
                Répondre
            </button>
            <button type="submit" name="preview" class="button secondary" {% if topic.is_locked or topic.antispam %}disabled{% endif %}>
                Prévisualiser
            </button>
        </div>
    </div>
    <input type="hidden" name="last_post" value="{{ last_post_pk }}" />
    {% csrf_token %}
</form>
{% endif %}

{% endblock %}

{% block additionnal-js %}
    {% if perms.forum.change_topic %}
        <script>
            $('.topic-actions .validate').click(function() {
                var lock = $('#lock-on').is(':checked');
                var sticky = $('#sticky-on').is(':checked');
                var solved = $('#solved-on').is(':checked');
                $.post('{% url "pdp.forum.views.edit" %}', {
                    topic: {{ topic.pk}},
                    op_lock: lock.toString(),
                    op_sticky: sticky.toString(),
                    op_solved: solved.toString(),
                })
            });
        </script>
    {% endif %}
    <script>
        /* anwser check */
        $('#submit_form').submit(function(e){
            if (!$(this).find('textarea').val()) {
                alert('Votre message ne peut pas être vide.');
                e.preventDefault();
            }
        })
        /* on button press, store it */
        $('#edit_form button[type="submit"]').on('click', function() {
            $('#edit_form').data('button', this.name);    
        });
        /* on submit */
        $('#edit_form').submit(function(e){
            e.preventDefault();
            /* build data */
            var button = $(this).data('button');
            var data = { topic: {{ topic.pk }}};
            data[button] = 'true';
            /* post data */
            $.post('{% url "pdp.forum.views.edit" %}', data, function(data){
                    if ('solved' in data) {
                        if (data.solved) {
                            $('#resolu').fadeIn();
                            $('#resolu_btn').removeClass('secondary');
                            $('#resolu_btn').addClass('success');
                            $('#resolu_btn').html('Résolu');
                        } else {
                            $('#resolu').fadeOut();
                            $('#resolu_btn').removeClass('success');
                            $('#resolu_btn').addClass('secondary');
                            $('#resolu_btn').html('Résolu ?');
                        }
                    }
                    if ('follow' in data) {
                        if (data.follow) {
                            $('#follow_btn').removeClass('secondary');
                            $('#follow_btn').html('Suivi');
                        } else {
                            $('#follow_btn').addClass('secondary');
                            $('#follow_btn').html('Suivre');
                        }
                    }
                }, 'json'); 
        });
    </script>
{% endblock %}